### ISSUE TITLE
Nested 'with' (CTE) expressions fail, and multiple INNER JOIN clauses are weird

### ISSUE THREAD

**Issue by mrflip** [ivank/potygen#55]
Thanks so much for this library, it is a gamechanger for debugging generated sql queries. Two issues parsing this expression, which postgres runs happily and correctly:

```sql
-- with "counting" AS (
WITH "base" AS (
    SELECT
      "Basketing"."vendingID", count(*) AS "totalCount", json_build_object('endCursor', '8e15'::varchar, 'hasNextPage', FALSE) AS "pageInfo"
    FROM "Basketing"
    WHERE "Basketing"."purchaseID" = 'pur.taco:taco_oban_c4' AND "Basketing"."typename" = 'Basketing' AND "Basketing"."okey" = 'taco'
    GROUP BY "Basketing"."vendingID", "Basketing"."tipID"
  )
SELECT * FROM "base" INNER JOIN "Vending" AS "vending" ON "base"."vendingID" = "vending"."id"
-- ) SELECT COUNT(*) FROM "counting"
```

The expression is a simplified version of a query generated by knex. I ran into two problems running `yarn prettier --plugin '@potygen/prettier-plugin-pgsql' /tmp/foo.sql` , with `"@potygen/potygen": "^0.6.8",    "@potygen/prettier-plugin-pgsql": "^0.6.8",`:

1. As written, the expression succeeds but the second INNER JOIN clause is rendered as `IN ner`:
    ```sql
    FROM
      "base"
      INNER JOIN "Vending" AS "vending"
        ON "base"."vendingID" = "vending"."id" IN ner
      JOIN "Product" AS "tip"
        ON "base"."tipID" = "tip"."id"
    -- ) SELECT COUNT(*) FROM "counting"
    ```
2. if you remove the comment markers on the first and last line (making it `with "counting" AS (with "base" AS ( ... ) SELECT COUNT(*) FROM "counting"`), it fails with this error:

```
../../../../../tmp/foo.sql[error] ../../../../../tmp/foo.sql: Error: Unexpected token at 2:1
[error]     at /Users/flip/code/mearth/.yarn/cache/@ikerin-rd-parse-npm-4.0.1-a7eb775516-68c1c041f2.zip/node_modules/@ikerin/rd-parse/dist/parser.js:247:19
[error]     at Object.parse (/Users/flip/code/mearth/.yarn/__virtual__/@potygen-prettier-plugin-pgsql-virtual-b3ad3d60ab/0/cache/@potygen-prettier-plugin-pgsql-npm-0.6.8-a9250c8410-4acfa21538.zip/node_modules/@potygen/prettier-plugin-pgsql/dist/index.js:442:56)
[error]     at Object.parse (/Users/flip/code/mearth/.yarn/cache/@potygen-prettier-npm-2.6.1-7f8851333d-bf20440065.zip/node_modules/@potygen/prettier/index.js:7339:23)
[error]     at coreFormat (/Users/flip/code/mearth/.yarn/cache/@potygen-prettier-npm-2.6.1-7f8851333d-bf20440065.zip/node_modules/@potygen/prettier/index.js:8650:18)
[error]     at formatWithCursor2 (/Users/flip/code/mearth/.yarn/cache/@potygen-prettier-npm-2.6.1-7f8851333d-bf20440065.zip/node_modules/@potygen/prettier/index.js:8842:18)
[error]     at Object.formatWithCursor (/Users/flip/code/mearth/.yarn/cache/@potygen-prettier-npm-2.6.1-7f8851333d-bf20440065.zip/node_modules/@potygen/prettier/index.js:40225:12)
[error]     at format (/Users/flip/code/mearth/.yarn/cache/@potygen-prettier-npm-2.6.1-7f8851333d-bf20440065.zip/node_modules/@potygen/prettier/cli.js:11977:24)
[error]     at formatFiles2 (/Users/flip/code/mearth/.yarn/cache/@potygen-prettier-npm-2.6.1-7f8851333d-bf20440065.zip/node_modules/@potygen/prettier/cli.js:12056:20)
[error]     at async main (/Users/flip/code/mearth/.yarn/cache/@potygen-prettier-npm-2.6.1-7f8851333d-bf20440065.zip/node_modules/@potygen/prettier/cli.js:12243:5)
[error]     at async Object.run (/Users/flip/code/mearth/.yarn/cache/@potygen-prettier-npm-2.6.1-7f8851333d-bf20440065.zip/node_modules/@potygen/prettier/cli.js:12190:5)
```

Is that enough to reproduce at your end? I can make a more focused test / gist if needed.

**Comment by ivank** [comment]
Nice! Thanks for finding this bug. I'll look into patching this as it is indeed undesirable behaviour
